name: Validate brands.json

on:
  push:
    paths:
      - brands.json
  pull_request:
    paths:
      - brands.json

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Validate brands.json
        run: |
          python .github/scripts/validate_brands.py

      - name: Auto-approve and merge
        if: contains(github.event.pull_request.user.login, 'HineshMandalia')
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    runs-on: ubuntu-latest
    needs: validate-json
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for mergeable state
        uses: actions/github-script@v6
        with:
          script: |
            let attempts = 0;
            const maxAttempts = 10;
            const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

            while (attempts < maxAttempts) {
              const { data: pullRequest } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });

              if (pullRequest.mergeable && pullRequest.mergeable_state === 'clean') {
                core.setOutput('mergeable', true);
                return;
              }

              attempts++;
              await delay(1000); // Wait 1 seconds before retrying
            }

            core.setOutput('mergeable', false);

      - name: Merge pull request
        if: steps.wait-for-mergeable-state.outputs.mergeable == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });