name: Validate brands.json

on:
  push:
    paths:
      - brands.json
  pull_request:
    paths:
      - brands.json

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Validate brands.json
        run: |
          python .github/scripts/validate_brands.py

      - name: Auto-approve and merge
        if: contains(github.event.pull_request.user.login, '@hinmantechnology/onefitai-ui')
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}